/* Writes the encrypted fixtures, one page each, with pdfio itself (design
 * section 15): tools/update-fixtures compiles this against the vendored
 * pdfio in src/vendor/pdfio. Not part of the package.
 *
 *   make-encrypted <outdir>
 *
 * Each file shows one line of Helvetica naming its method and carries a
 * Title. The "-pw" files have user password "user" and owner password
 * "owner" and forbid printing; the others have no password and allow
 * everything. Encryption keys are random, so the bytes differ on every
 * run; the files are committed, not regenerated by the tests. */

#include <stdio.h>
#include <string.h>

#include "pdfio.h"
#include "pdfio-content.h"

static bool error_cb(pdfio_file_t *pdf, const char *message, void *data)
{
  (void)pdf;
  (void)data;
  fprintf(stderr, "make-encrypted: %s\n", message);
  return false;
}

static int write_one(const char *dir, const char *name, pdfio_encryption_t enc,
                     const char *label, int with_passwords)
{
  char path[1024];
  snprintf(path, sizeof(path), "%s/%s", dir, name);
  pdfio_rect_t box = {0.0, 0.0, 612.0, 792.0};
  pdfio_file_t *pdf = pdfioFileCreate(path, "1.7", &box, &box, error_cb, NULL);
  if (!pdf)
    return 1;
  pdfio_permission_t perm = with_passwords ? (PDFIO_PERMISSION_ALL ^ PDFIO_PERMISSION_PRINT)
                                           : PDFIO_PERMISSION_ALL;
  if (!pdfioFileSetPermissions(pdf, perm, enc, with_passwords ? "owner" : NULL,
                               with_passwords ? "user" : NULL))
    return 1;
  pdfioFileSetTitle(pdf, label);
  pdfioFileSetAuthor(pdf, "zupdf fixtures");
  pdfio_obj_t *font = pdfioFileCreateFontObjFromBase(pdf, "Helvetica");
  pdfio_dict_t *dict = pdfioDictCreate(pdf);
  if (!font || !dict || !pdfioPageDictAddFont(dict, "F1", font))
    return 1;
  pdfio_stream_t *st = pdfioFileCreatePage(pdf, dict);
  if (!st)
    return 1;
  int ok = pdfioContentTextBegin(st) && pdfioContentSetTextFont(st, "F1", 12.0) &&
           pdfioContentTextMoveTo(st, 72.0, 720.0) &&
           pdfioContentTextShow(st, false, label) && pdfioContentTextEnd(st);
  ok = pdfioStreamClose(st) && ok;
  ok = pdfioFileClose(pdf) && ok;
  return ok ? 0 : 1;
}

int main(int argc, char **argv)
{
  if (argc != 2) {
    fputs("usage: make-encrypted <outdir>\n", stderr);
    return 2;
  }
  int status = 0;
  status |= write_one(argv[1], "encrypted-rc4-128.pdf", PDFIO_ENCRYPTION_RC4_128, "Encrypted with RC4-128", 0);
  status |= write_one(argv[1], "encrypted-rc4-128-pw.pdf", PDFIO_ENCRYPTION_RC4_128, "Encrypted with RC4-128 and passwords", 1);
  status |= write_one(argv[1], "encrypted-aes-128.pdf", PDFIO_ENCRYPTION_AES_128, "Encrypted with AES-128", 0);
  status |= write_one(argv[1], "encrypted-aes-128-pw.pdf", PDFIO_ENCRYPTION_AES_128, "Encrypted with AES-128 and passwords", 1);
  return status;
}
